version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roullete_jupyter_container  # Set a custom container name
    image: roullete-jupyter-image:latest    # Set a custom image name and tag
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app
