version: '3.8'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mth_500_container  # Set a custom container name
    image: mth-500-image:latest    # Set a custom image name and tag
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app
